title: Jim Rossiter  # your name (or website title) here
logo: "IMG_20240405_014232.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst & experienced Maths secondary school teacher. Avid sports fan. 
  Track my work below. Open to networking and discussion of work.
  <br><br>
  <a href="https://www.linkedin.com/in/jim-rossiter-766a361a5?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app">View My LinkedIn Profile</a>  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
