title: Jim Rossiter  # your name (or website title) here
logo: "IMG_20240405_014232.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Analyst & an experienced Maths Secondary School teacher. Avid sports fan. Open to networking and discussion of work.
  <br><br>
  <a href="https://www.linkedin.com/in/jim-rossiter-766a361a5?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://Jimrossiter.github.io"><img src="/images/25694.png" alt=\"House\" style=\"width: 30px; height: 30px;\"></a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
